### ISSUE TITLE
Support last version of ES and NEO4J ? 

### ISSUE THREAD

**Issue by falkenlabs** [octaldata/streamops#15]
Hi, 
I have tried to install your latest version of the elasticsearch river for neo4j (1.1.1) but it seems that it don't support the latest version of neo4j 2.1.1 and elasticsearch 1.2.1.

After sever hours of testing the plugins doesn't load in elasticsearch !?
Do you plan to support latest version ? 

Regards.

**Comment by pauleil** [comment]
Does this plugin work with ES 1.5?
