### ISSUE TITLE
Migration of this river to a logstash input and output

### ISSUE THREAD

**Issue by purbon** [octaldata/streamops#23]
Good morning,
  I've just created an input [1] and output [2] for neo4j in logstash, I will be very happy to extend it's functionality with the features in here, is this ok for you? If you're happy with ruby, obviously take a look at it and contribute if you like to :-) everything is welcome!

/cheers

[1] https://github.com/logstash-plugins/logstash-input-neo4j
[2] https://github.com/logstash-plugins/logstash-output-neo4j

**Comment by sksamuel** [comment]
Yes sure.

**Comment by purbon** [comment]
I'll do @sksamuel, if you've anything you find useful from this river that aim to see in the logstash plugin, let me know :-)
